### ISSUE TITLE
kNN evaluation during training

### ISSUE THREAD

**Issue by elias-ramzi** [facebookresearch/simsiam#10]
Hi, tank you for the repository !

I was wondering if you were planning to release the code for the kNN evaluation used during training ?

Thanks

**Comment by endernewton** [comment]
We have no plan to release the code for KNN. But the implementation of KNN is following the memory bank paper. Roughly speaking, after each epoch, we extract pool-5 features (l2-normalized) for each image in the training set, and conduct a 200-NN with the dot-product of features as weights (temperature 0.2).

**Comment by elias-ramzi** [comment]
Thanks !
