### ISSUE TITLE
Stuck in the DDP initiliazation step

### ISSUE THREAD

**Issue by kxgong** [facebookresearch/simsiam#16]
Hello,
I use the example command to run the pretraining script, but i will get stuck in this line

```dist.init_process_group(backend=args.dist_backend, init_method=args.dist_url, world_size=args.world_size, rank=args.rank)```

Should I change the configuration? I run this on a single node (gpu server) using two GPUs. And I use the 'CUDA_VISIBLE_DEVICES' to sepcify the gpu ids. Looking forward to your reply.

**Comment by mrezaei92** [comment]
I think you should only set this argument --dist-url for local use, like  --dist-url 'tcp://localhost:10001'

**Comment by endernewton** [comment]
Looks like it is resolved? Anyhow the stuck of initialization can be caused by many factors. I recommend you first test the PyTorch DDP to see if it works, before trying the code base.
