### ISSUE TITLE
l2 normalize

### ISSUE THREAD

**Issue by UQ-DongYuan** [facebookresearch/simsiam#17]
Hi,

Based on your original paper, you mentioned that p and z should be l2 normalized, but I cannot find the l2-normalize process in this code. Could you give me any help?

Cheers

**Comment by xro7** [comment]
@UQ-DongYuan Did you figure this out? I don't see any normalization in the code.

**Comment by aqweteddy** [comment]
@xro7 I think L2 normalization process is contained in nn.CosineSimilarity.
