### ISSUE TITLE
Learning rate scheduler setting for different epochs

### ISSUE THREAD

**Issue by BaohaoLiao** [facebookresearch/simsiam#22]
Hi,

in the Table 4 of your paper, you compared the results of different epochs. May I ask you what's the difference of the learning rate scheduler settings for theses epochs?

I think there are two options we can use:

1. You conduct only one experiment and set the max epoch to 800, then select 100, 200, 400, 800 ep.
2. You conduct four experiments and set the max epoch to 100, 200, 400, and 800.

Want to make sure which one did you use, since their lr schedulers are different.

**Comment by endernewton** [comment]
We conducted experiments setting the max epoch. So 2.
