### ISSUE TITLE
Questions about the optimal model for object detection

### ISSUE THREAD

**Issue by bluenights** [facebookresearch/simsiam#24]
Thanks for the great work! In the paper, the encoder lr is set to 0.5 (instead of 0.05) for training the optimal model on object detection. I'm wondering what the predictor's learning schedule is. Is it a constant 0.5? Would it be too large for the whole 200 epoch training?

**Comment by endernewton** [comment]
Yes a constant 0.5 iirc. Note that wd is also changed.

**Comment by bluenights** [comment]
Thanks for the answer!
