### ISSUE TITLE
Question about the calculated details of std in the paper

### ISSUE THREAD

**Issue by qxm1995716** [facebookresearch/simsiam#25]
Thanks for your excellent work, it's very impressive.
However, I am confused about the detail in the calculation of std in the paper. In your paper, obviously that output should be L2_normed, which is z' = z / ||z||. In the footnote 3, you say that zi = zi / (sum(zj, j=1~d))^(1/2), but what is the meaning of i and j here?  If z is the output of input with N samples (which mean z's size should be N rows and d columns, namely N x d),  is the i meaning the index of rows and j mean the index of columns? Therefore, the std is calculated by columns by columns (per channel), that is, std(z) should be a sum of 1xd vector?

**Comment by endernewton** [comment]
i is sample index and j is dimension index. so i for N, and j for d. std(z) is w.r.t. the whole vector, not values. hope it is clear?

**Comment by qxm1995716** [comment]
Thanks for your answer!
