### ISSUE TITLE
zero_init_residual

### ISSUE THREAD

**Issue by ifountalis** [facebookresearch/simsiam#28]
Hi, 

In the model builder for SiamSiam we observe the following scheme for the encoder initialization:

self.encoder = base_encoder(num_classes = dim, zero_init_residual = True);

From our understanding this is mostly applicable to ResNETs.  (a) Is that zero initialization of the last batch norm layers
important? (b) What about other architectures?

**Comment by endernewton** [comment]
Yes it is mostly for resnets. Honestly we haven't experimented much beyond this architecture. For ResNet it is quite important for stability iirc -- you can try to turn it off and see if anything interesting/strange happens.
