### ISSUE TITLE
loss question

### ISSUE THREAD

**Issue by daeing** [facebookresearch/simsiam#29]
I use others data  augmentation. the loss go down to -1 in the first epoch, and then go up slowly in the next epoch?  Have you meet the same problem when you try differnet data augmentation?

**Comment by vincezengqiang** [comment]
I meet the same question, loss is small in first epoch, but it go up slow in next epoch. 
Is now the problem solved?

**Comment by milliema** [comment]
I have similar question. Within several iterations, the loss converges to -1 (which is the minimum ideal value), and then remains stable. Does it mean, the model has learned a collapsing solution?

**Comment by endernewton** [comment]
SimSiam is indeed sensitive to augmentations. With a different augmentation recipe one may need to adjust lr or other hyper-parameters.

**Comment by godkaieethu** [comment]
same problem with you.Do you have any idea to fix it now?
