### ISSUE TITLE
Loss descent slowly

### ISSUE THREAD

**Issue by vincezengqiang** [facebookresearch/simsiam#31]
Thanks for your excellent work firstly!
When I use my own dataset, the loss begin with 0.001, and then descend slowly, after 100 epoch the loss is about 0.1, is this normal? Thanks!

**Comment by endernewton** [comment]
I am not sure what you mean without the context. In general, loss curve decreases like what's shown in the paper. We have not tried on other dataset, but if the loss increases, it is generally not a good sign (unless the underlying data distribution changes).
