### ISSUE TITLE
SyncBatchnorm usage in main_lincls.py

### ISSUE THREAD

**Issue by myoh97** [facebookresearch/simsiam#38]
Hello, Thanks for your great work. I have a short question.

Is there a reason why you use syncbatchnorm in main_simsiam.py only?
I can't find use of it in main_lincls.py.
Doesn't it matter?

Thanks!

**Comment by HuangChiEn** [comment]
Hello, maybe related with following issue
https://github.com/pytorch/pytorch/issues/48988

**Comment by HuangChiEn** [comment]
> Hello, maybe related with following issue
> [pytorch/pytorch#48988](https://github.com/pytorch/pytorch/issues/48988)

Hello, maybe related with following issue
https://github.com/pytorch/pytorch/issues/48988

**Comment by HuangChiEn** [comment]
> Hello, Thanks for your great work. I have a short question.
> 
> Is there a reason why you use syncbatchnorm in main_simsiam.py only? I can't find use of it in main_lincls.py. Doesn't it matter?
> 
> Thanks!

Hello, maybe related with following issue
https://github.com/pytorch/pytorch/issues/48988

**Comment by endernewton** [comment]
It does not matter as BNs in linear eval are in testing mode, using pre-trained stats.
