### ISSUE TITLE
Open-source improved implementations of BYOL, SWAV, etc.?

### ISSUE THREAD

**Issue by LinxiFan** [facebookresearch/simsiam#5]
Thank you so much for open-sourcing! The code looks extremely clean and nice. It is a great service to the community! 

Would you also open-source the improved implementations of BYOL, SWAV, SimCLR and MoCoV2? Devils are in the details, so it would be great to reproduce the improved baselines results in the paper as well. 

Thanks again for your wonderful work!

**Comment by endernewton** [comment]
We don't have plans to release code for those methods as their official codes are already released and our implementations on TPUs, not GPUs like this code. 

We do have a MoCo v3 code to be released which can achieve better results (74.5+ with 2 224 crops) than all the methods mentioned above on GPUs, though it will require 32 or 64 GPUs to train. Please stay tuned.

**Comment by LinxiFan** [comment]
That's amazing. I look forward to MoCo V3 release. Thanks again!

**Comment by endernewton** [comment]
We released code of MoCo v3 at https://github.com/facebookresearch/moco-v3
