### ISSUE TITLE
Why BYOL without the momentum encoder collapses but SimSiam does not?

### ISSUE THREAD

**Issue by zhujiagang** [facebookresearch/simsiam#7]
Thank you for releasing the code. A great work! As your paper says: "Our method can be thought of as “BYOL without the momentum encoder”, subject to many implementation differences." When the learning rate of predictor is the same as other parts of network, why BYOL without the momentum encoder collapses but SimSiam does not? Is it due to the implementation differences? Hope my understanding of BYOL and SimSiam to be right.

**Comment by endernewton** [comment]
This is not a code related issue. We empirically observed SimSiam does not collapse but with BYOL's design it did. It's good to get to a more theoretical understanding of it and the answer remains open to the best of our knowledge.
